[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4==4.12.3",
    "notion-client>=2.2.1",
    "requests==2.32.3",
    "selenium>=4.26.1",
]
